---
- debug: msg="(( Clean Kismet installation. ))"

- name: Check if '{{ warpi_service_name }}.service' systemd file exists.
  stat: path="/etc/systemd/system/{{ warpi_service_name }}.service"
  register: my_systemd_service_file

- name: Stopping and disabling '{{ warpi_service_name }}.service' systemd.
  service:
    name: "{{ warpi_service_name }}"
    enabled: no
    state: stopped
  when: my_systemd_service_file.stat.exists

- find:
    paths:
      - "/home/{{ ansible_ssh_user }}/"
      - "{{ kismet_conf_log }}"
      - "/etc/systemd/system/"
    patterns: "^(.kismet|kismet|Kismet|{{ warpi_service_name }}).*$"
    use_regex: True
  register: kismet_files_to_cleanup

- name: Deleting all related Kismet .deb, .sh, log and pcap files.
  file:
    name: "{{ item.path }}"
    state: absent
  with_items: "{{ kismet_files_to_cleanup.files }}"

- name: Uninstalling Kismet package and dependencies.
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - kismet
    - libncurses5-dev
    - libpcap-dev
    - libpcre3-dev
    - libnl-dev
  when: "{{ kismet_remove_dependencies }}"
